import config as main_config


DEFAULT_BUTTON_WIDTH = 300
HYPERPARAMS_BUTTON_WIDTH = 200
INDENT = main_config.DW // 60
SWITCH_PANEL_BUTTON_WIDTH = DEFAULT_BUTTON_WIDTH
PADDING_BUTTONS_HYPERPARAMS = 10
