class WindowTag:
    PRIMARY_WINDOW = 'PRIMARY_WINDOW' 
    SWITCH_PANEL_WINDOW = 'SWITCH_PANEL_WINDOW'


class WorkspaceWindowTag:
    CONSTRUCTOR = "CONSTRUCTOR_WORKSPACE_WINDOW"
    TRAIN = "TRAIN_WORKSPACE_WINDOW"

